#THIS IS ABOUT LOOPS IN PYTHON
#LOOPS ARE USED TO REPEAT A BLOCK OF CODE MULTIPLE TIMES
#THERE ARE TWO TYPES OF LOOPS IN PYTHON: FOR LOOPS AND WHILE LOOPS
#FOR LOOPS ARE USED TO ITERATE OVER A SEQUENCE (LIKE A LIST, TUPLE, STRING, OR RANGE)
#WHILE LOOPS ARE USED TO REPEAT A BLOCK OF CODE AS LONG AS A CONDITION IS TRUE
#EXAMPLE OF A FOR LOOP
for i in range(5):
    print(i)
#EXAMPLE OF A WHILE LOOP
count = 0
while count < 5:
    print(count)
    count += 1
#LOOPS CAN ALSO BE NESTED (A LOOP INSIDE ANOTHER LOOP)
for i in range(3):
    for j in range(2):
        print(f'i: {i}, j: {j}')
#LOOPS CAN ALSO BE USED WITH ELSE STATEMENT
for i in range(5):
    print(i)